'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Table
    Public Property Id As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property EmailAddress As String
    Public Property DateOfBirth As Date
    Public Property CarYear As Integer
    Public Property CarMake As String
    Public Property CarModel As String
    Public Property DUI As Boolean
    Public Property SpeedingTickets As Integer
    Public Property CoverageType As Boolean
    Public Property Quote As Decimal

End Class
